Added support for one-to-many relations
Glifery/EntityHiddenTypeBundle pull request #10
Opened 2016-11-09 08:32 UTC by tkuska

Now we can pass collection of entities to form field instead of single entity.

2016-12-24 00:32 UTC, Glifery commented
Hi @tkuska.
Thanks for the work! We're preparing this repo for symfony 3 support. And it should be done first. So I'll review your PR and merge it asap.
Actually you can help us to prepare your PR to symfony 3. All you need to do is to merge a `symfony-3-support` branch into your PR's branch and make sure all works. Thanks!

2017-04-15 07:58 UTC, tkuska commented
It looks like everything works fine after merge `symfony-3-support` branch

2017-04-15 12:44 UTC, Glifery requested changes
Hi @tkuska.
Great work! Now we can merge it.
By the way there are some codestype problems that should be fix. Please take a look my review

2017-04-15 12:44 UTC, Glifery commented on Form/DataTransformer/ObjectToIdTransformer.php
> +class ObjectToIdTransformer implements DataTransformerInterface {
According to [4.1. Extends and Implements (PSR-2)](http://www.php-fig.org/psr/psr-2/#extends-and-implements)
> The opening brace for the class MUST go on its own line;

please fix this

2017-04-15 12:44 UTC, Glifery commented on Form/DataTransformer/ObjectToIdTransformer.php
> +    public function __construct(ManagerRegistry $registry, $om, $class, $property, $multiple = false) {
According to [4.3. Methods (PSR-2)](http://www.php-fig.org/psr/psr-2/#methods)
> The opening brace MUST go on its own line,

please fix this
(note that there are a couple of places in code that should be fixed)

2017-04-15 14:58 UTC, tkuska commented
fixed :)

2017-04-18 06:54 UTC, tkuska commented
now it's fixed, i misunderstood your previous comment

2017-07-18 22:28 UTC, merged